"""password was added to user

Revision ID: a45dbafd4392
Revises: f2d986c7de82
Create Date: 2023-06-02 16:05:27.048125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a45dbafd4392"
down_revision = "f2d986c7de82"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("email", sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column("password", sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("password")
        batch_op.drop_column("email")

    # ### end Alembic commands ###
