"""was deleted email from user

Revision ID: f2d986c7de82
Revises: f2b6f2d7b92c
Create Date: 2023-05-31 12:27:50.488027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d986c7de82'
down_revision = 'f2b6f2d7b92c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=128), nullable=True))

    # ### end Alembic commands ###
